name: Daily IPL Scraper

on:
  schedule:
    - cron: '30 18 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    # This line fixes the Node.js 20 warning
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager gspread oauth2client
          
      - name: Run Scraper
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        # Check your repository! If the file is named 'scraper.py', change it below.
        run: python scrapper.py
